version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'pool_party'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./database/volumes:/var/lib/mysql
